# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OneBuild < Formula
  desc "Frictionless way of managing project-specific commands"
  homepage "https://github.com/gopinath-langote/1build"
  version "1.10.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.2/1build_Darwin_x86_64.tar.gz"
      sha256 "830a856d9b25ada40bd577fa9706f8f276b8dfc3b3be10e203a9146bc4318461"

      define_method(:install) do
        bin.install "1build"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.2/1build_Darwin_arm64.tar.gz"
      sha256 "94f8b3bce066e37732e9f4553f70f9f317ec5caba9081ec47b5ec14b76057260"

      define_method(:install) do
        bin.install "1build"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.2/1build_Linux_x86_64.tar.gz"
      sha256 "fd28852a51ca8f69917a478d7fc758e9f4d3f483102f7e648660d71adecb474f"
      define_method(:install) do
        bin.install "1build"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.2/1build_Linux_arm64.tar.gz"
      sha256 "b76a81dee7e0da98f0f5b158f115f0e9903471c8ade0375927ed9a82fc6c0fb4"
      define_method(:install) do
        bin.install "1build"
      end
    end
  end

  test do
    system "#{bin}/1build --version"
  end
end
