# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OneBuild < Formula
  desc "Frictionless way of managing project-specific commands"
  homepage "https://github.com/gopinath-langote/1build"
  version "1.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.1/1build_Darwin_x86_64.tar.gz"
      sha256 "90734b768adf771e1e911f56a93284fcc3071e167375f241175a927a90b7ee9c"

      define_method(:install) do
        bin.install "1build"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.1/1build_Darwin_arm64.tar.gz"
      sha256 "3dbb07a2fb74c8afa65653470fba5a45ea35a784845f5556686fa612e73b23e1"

      define_method(:install) do
        bin.install "1build"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.1/1build_Linux_x86_64.tar.gz"
      sha256 "7351750bca0aa8cd4f91e6540698d7eab43f5e9ecbd96e49f5934c76d758c38d"
      define_method(:install) do
        bin.install "1build"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.10.1/1build_Linux_arm64.tar.gz"
      sha256 "aaf93bf346372bd24a273e363b23dff1dd43c786218f94fe97ef25bcfbdfa656"
      define_method(:install) do
        bin.install "1build"
      end
    end
  end

  test do
    system "#{bin}/1build --version"
  end
end
